# Generated by Django 5.0.7 on 2024-07-21 17:57

import shuffle.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0002_invitation_round_payment_delete_contribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasanakugroup',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='pasanakugroup',
            name='payment_day',
            field=models.PositiveIntegerField(default=1, validators=[shuffle.validators.validate_payment_day]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasanakugroup',
            name='rounds',
            field=models.PositiveIntegerField(default=6),
            preserve_default=False,
        ),
    ]
