# Generated by Django 5.0.7 on 2024-07-21 23:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0003_remove_pasanakugroup_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasanakugroup',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasanakugroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
